baseURL = "http://blog.nafiux.com/"
languageCode = "en-us"
title = "Nafiux Blog"
theme = "hugo-theme-minos"
disqusShortname = "blognafiux"

[params]
    smartToc = true

[[menu.main]]
    name = "About"
    pre = "<i class='fa fa-heart'></i>"
    weight = -110
    identifier = "about"
    url = "/profile"
