baseurl = "http://blog.ignacio.org.mx"
title = "Ignacio Ocampo"
copyright = "© 2017-2019 Ignacio Ocampo"
languageCode = "en-us"
theme = "minimo"

[permalinks]
blog  = "/blog/:year/:month/:title/"
page  = "/:slug/"

[taxonomies]
tags = "tags"

[[menu.main]]
weight = 1
name = "Posts"
url = "/posts/"

# Minimo theme configuration

paginate = 5
enableRobotsTXT = true # generate robots.txt
enableEmoji = true

[params.info]
description = "Engineering Manager / Solutions Architect"

[params.sidebar]
enable = true

[params.widgets]
header = ["breadcrumbs"]
homepage = ["recent_posts"]
sidebar = ["about","sidebar_menu","taxonomy_cloud"] # search
footer = ["social_menu"]

[params.social]
email = "nafiux@gmail.com"
github = "iocampomx"
linkedin = "iocampomx"
twitter = "iocampomx"

[params.settings]
accentColor = "#00f"
